### PR TITLE
Do not keep open for image vo driver

### PR DESCRIPTION
**Pull request by teohhanhui**
There is no GUI.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Hi, sorry that it's taken so long to see that, I got no notifications about this, and I have no idea why Github didn't notify me about this pull request...

I wouldn't have seen it at all if I didn't just randomly see that you had forked my repo, and I clicked it to see if you were doing any work. Weird.

Anyway, the purpose of this change seems to be: If you open an image file (which uses the video output), you don't want it to enable keep-open. So you only want it to use keep-open mode if you're playing video files, but not image files or audio files. So if the final file is reached and is an image file, you want the window to close itself.

That seems like a fine idea. But this is implemented incorrectly. You've placed a "if video output == image mode, abort loading of this script completely". That means that your code doesn't handle playlists properly. A playlist can change back and forth between videos and audio and image files.

Your proposal needs to be rewritten to put the code in the proper place inside the `mp.observe_property()` section at the bottom of this script. Unfortunately I have health issues right now and have no energy to do a proper rewrite. I'll leave this pull request open if you want to rewrite it? Just look at my original code, and place your changes somewhere inside the `-- Video output has been created.` section. That's where the "is it an image? don't use keep-open" code would go.

I also think this should probably have a configuration variable. Some people may want ALL GUIs (even images) to stay open after reaching the final file, which is what keep-open=yes does.

**Comment by teohhanhui** [comment]
The `image` vo driver is saves screenshots from a video, instead of rendering the video on screen. It has nothing to do with loading image files.

**Comment by SteveJobzniak** [comment]
Aaaaaah now I understand... so it's a video output driver which writes to disk, and has no GUI. Gotcha!

But I wonder if we should put this check further down in the file?

Perhaps like this:

```lua
if (mp.get_property("config") ~= "no") then
    local originalKeepOpenValue = mp.get_property("keep-open")

    -- This runs with "false" at mpv initialization (before the playback
    -- of the first file), regardless of whether that file will use
    -- video output or not. After that, it runs whenever the video
    -- output (usually a GUI window) is created or destroyed. So if the
    -- first file is a video, it runs twice at startup (false -> true).
    --
    -- Implementation details:
    -- vo-configured == video output created && its configuration went ok.
    -- What that means depends on the platform-specific video output module,
    -- but usually it means there is a GUI on screen to display video.
    mp.observe_property(
        "vo-configured",
        "bool",
        function (name, value)
            if (value and mp.get_property("vo") ~= "image") then
                -- Video output (usually a GUI) has been created.
                -- NOTE: We ignore the "image" vo driver, which has no GUI and writes to disk.

                if (AKGO_WINDOW_KEEP_OPEN_VALUE == "original") then
                    mp.set_property("keep-open", originalKeepOpenValue)
                else
                    mp.set_property("keep-open", AKGO_WINDOW_KEEP_OPEN_VALUE)
                end

                if (AKGO_USE_WINDOW_FOR_AUDIO_AFTER_VIDEO) then
                    mp.set_property("force-window", "yes")
                end
            else
                -- Video output (usually a GUI) has been destroyed.

                if (AKGO_NOWINDOW_KEEP_OPEN_VALUE == "original") then
                    mp.set_property("keep-open", originalKeepOpenValue)
                else
                    mp.set_property("keep-open", AKGO_NOWINDOW_KEEP_OPEN_VALUE)
                end
            end
    end)
end
```

**Comment by SteveJobzniak** [comment]
The changes I made are these 3 lines:

```lua
            if (value and mp.get_property("vo") ~= "image") then
                -- Video output (usually a GUI) has been created.
                -- NOTE: We ignore the "image" vo driver, which has no GUI and writes to disk.
```

Basically: Anytime the video output is opened/closed, it checks the value. If the value is true (we are using video output) AND we are NOT using the "image file" video driver, it runs the "handle a GUI" code. Else it runs the "handle CLI" code.

Does my proposed idea sound fine?

**Comment by SteveJobzniak** [comment]
I finally had time to look at this and have merged the fix I proposed above. Thanks for your report! :-)

https://github.com/SteveJobzniak/mpv-tools/commit/d8eaf44ef10bfd3ec4bd07d86b16f8925aad8e87

**Pull request closed without merging**
